### ISSUE TITLE
배포 버전 1.0.0

### ISSUE THREAD

**Issue by jaehan4707** [mini-moment/mimo-android#100]
## descriptions
- 배포 버전 1.0.0

## TODO
- [x] 칩 디자인 변경
- [x] 개인정보 처리 방침 WebView 연결
- [x] 마이 페이지에서 게시물 누르면 터지는 버그 해결
- [x] 마커 아이콘 변경
- [x] 코드 정렬
- [x] 패키지 변경
