### ISSUE TITLE
영상 좋아요 UI 구현

### ISSUE THREAD

**Issue by jaehan4707** [mini-moment/mimo-android#116]
## descriptions
- 영상 좋아요 UI 구현

## TODO
- [ ] 영상 좋아요 이미지 리소스
- [ ] 클릭 이벤트 처리
- [ ] 화면 더블 클릭 시 애니메이션 처리
