### ISSUE TITLE
영상 상세 화면 만들기

### ISSUE THREAD

**Issue by pooya98** [mini-moment/mimo-android#22]
# description
영상 상세 화면 UI 구현
# TODO
- [x] Media3 ExoPlayer gradle 추가 
- [x] 영상 상세 화면 UI 구현
- [x] 영상 재생 테스트
