### ISSUE TITLE
바텀 네비게이션 아이콘,영상 업로드 아이콘,영상 업로드로 화면 전환

### ISSUE THREAD

**Issue by ho-taek** [mini-moment/mimo-android#27]
## Todo
- [x] 바텀 네비게이션 아이콘 설정
- [x] 영상 업로드 아이콘
- [x] 영상 업로드 화면 전환
