### ISSUE TITLE
영상 상세 구조 변경 및 ViewPager 연결

### ISSUE THREAD

**Issue by pooya98** [mini-moment/mimo-android#47]
## Description
- VideoDetail Fragment에서 VideoDetail Activity로 변경
- ViewPager를 통해 여러 개 영상 볼 수 있도록 변경

## Todo
- [x] PostItem UI 구현
- [x] PostList Adapter 구현
- [x] VideoDetail Fragment -> ViewDetail Activity 구조 변경
- [x] Post 데이터 연결
