### ISSUE TITLE
게시글 리스트 불러오는 코드 및 마커 클릭 이벤트 수정

### ISSUE THREAD

**Issue by ho-taek** [mini-moment/mimo-android#64]
## Description
마커 클릭시 게시글 리스트 불러오고, 성공시 데이터 넘기기 및 바텀시트 UI 바인딩

## Todo
- [ ] 마커 클릭시 게시글 리스트 불러오기
- [ ] 게시글 리스트 네트워크
- [ ] 바텀시트 UI 바인딩
