### ISSUE TITLE
UI 수정

### ISSUE THREAD

**Issue by jaehan4707** [mini-moment/mimo-android#84]
## descriptions
- 텍스트 자간 줄이기
- 비디오 디테일 프로필 이미지 크기 수정
- chipIconSize 수정
- 네이버 로그인 크기 조절
## TODO
- [x] fontStyle letterSpacing 크기 조절
- [x] 비디오 디테일 프로필 이미지 크기 조절
- [x] 칩 아이콘 사이즈 줄이기
- [x] 네이버 로그인 버튼 크기 조절
