### ISSUE TITLE
바텀네비게이션 UI 수정

### ISSUE THREAD

**Issue by jaehan4707** [mini-moment/mimo-android#88]
## descriptions
- 바텀 네비게이션 UI 수정
## TODO
- [x] 텍스트 크기 조절
- [x] 텍스트 폰트 적용
- [x] 업로드 버튼 네비게이션으로 변경
